openapi: 3.1.0
info:
  title: AltruxApi
  description: Title
  version: 1.0.0
servers:
  - url: 'https://api.altrux.co.jp'
    
paths:
  /kolconnect/dashboard/byService:
    get:
      summary: サービス別契約状況取得
      description:
        指定したインフルエンサー（KOL）に紐づく、サービス別の契約状況とポイントブースト加入者数を取得する

      parameters:
        - name: kol_id
          in: query
          description: インフルエンサーID
          required: true
          schema:
            type: integer
            example: 1

      responses:
        "200":
          description: 正常レスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DashboardByServiceResponse"
        
        "400":
          description: リクエスト不正（kol_id不正など）
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    DashboardByServiceResponse:
      type: object
      properties:
        kol_id:
          type: integer
          example: 1
        total_subscribers:
          type: integer
          description: active契約の総数
          example: 25
        boost_subscriber_count:
          type: integer
          description: ポイントブースト加入者数
          example: 5
        services:
          type: array
          items:
            $ref: "#/components/schemas/ServiceSummary"

    ServiceSummary:
      type: object
      properties:
        category:
          type: string
          description: サービス区分
          example: mobile
        subscribers:
          type: integer
          description: 契約者数（active）
          example: 12
        new_contracts:
          type: integer
          description: 当月新規契約数（過去30日）
          example: 6
        cancellations:
          type: integer
          description: 当月解約数（過去30日）
          example: 1
        share:
          type: number
          format: float
          description: 全体に占める割合（％）
          example: 48.0

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: Database error
        detail:
          type: string
          example: Table 'contracts' doesn't exist

