openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths: 
  /health:
    get:
      tags:
        - health
      summary: health check

  /BMI:
    post:
      tags:
        - BMI
      deprecated: false
      x-42c-no-authentication: false
      x-42c-mtls: false
      x-42c-sensitivity: 3
      x-42c-weight-input: 80
      x-42c-weight-output: 20
      x-42c-weight-parameters: 50
      x-42c-weight-requestBody: 50
  
  /BMI/weight:
      get:
        tags:
          - BMI
        summary: my weight
    
